function [fitresult, gof] = splinesurface(x1, z1, y1,vis)
%splinesurface(X1,Z1,Y1)
%  Create a fit.
%
%  Data for thin-plate spline fit:
%      X Input : x1
%      Y Input : z1
%      Z Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Jun-2020 12:42:39


%% Fit: thin-plate spline
[x2, z2, y2] = prepareSurfaceData( x1, z1, y1 );

% Set up fittype and options.
ft = 'thinplateinterp';

% Fit model to data.
[fitresult, gof] = fit( [x2, z2], y2, ft, 'Normalize', 'on' );

if nargin>3
% Plot fit with data.
figure( 'Name', 'thin-plate spline fit' );
h = plot( fitresult, [x2, z2], y2 );
% legend( h, 'untitled fit 1', 'y1 vs. x1, z1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'x1', 'Interpreter', 'none' );
% ylabel( 'z1', 'Interpreter', 'none' );
% zlabel( 'y1', 'Interpreter', 'none' );
grid on
view( 99.1, 56.1 );
end

